language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - (composer self-update; true)
  - composer install

script:
  - phpunit tests/DeviceDetectorTest.php

notifications:
  irc:
    skip_join: true
    on_success: change
    channels:
      - "irc.freenode.org#piwik-dev"
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Device Detector Build details: %{build_url}"